### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Back-City** [0xlane/wechat-dump-rs#7]
确认包含Misc.db文件，并且存在多个Misc.db（qq也存在Misc.db文件）
报错：
┌──(Tom💀TEST)-[~/Downloads]                                                                                    0ms  ✓
└─# .\wechat-dump-rs.exe
[+] wechat version is 3.9.7.29
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 27, error_len: Some(1) }', src\procmem\mod.rs:44:96
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
NativeCommandExitException: Program "wechat-dump-rs.exe" ended with non-zero exit code: 101.
┌──(Tom💀TEST)-[~/Downloads]                                                                                  356ms  ⨯
└─# .\wechat-dump-rs.exe -a
[+] wechat version is 3.9.7.29
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 27, error_len: Some(1) }', src\procmem\mod.rs:44:96
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
NativeCommandExitException: Program "wechat-dump-rs.exe" ended with non-zero exit code: 101.
┌──(Tom💀TEST)-[~/Downloads]                                                                                   63ms  ⨯
└─# .\wechat-dump-rs.exe -p 14644
[+] wechat version is 3.9.7.29
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Utf8Error { valid_up_to: 27, error_len: Some(1) }', src\procmem\mod.rs:44:96
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
NativeCommandExitException: Program "wechat-dump-rs.exe" ended with non-zero exit code: 101.

**Comment by 0xlane** [comment]
看报错是进程模块文件路径中有一些特殊字符导致 [GetMappedFileNameA](https://github.com/0xlane/wechat-dump-rs/blob/4705a1a71990f2d96c93c896070fc8dae06f2012/src/procmem/mod.rs#L41C37-L41C55) 获取到了乱码

能发一下你的微信路径吗？我测试的时候路径都是全英文的，还没测试过其它情况。

**Comment by 0xlane** [comment]
这个我复现了，用的 GetMappedFileNameA 的关系如果路径中包含中文就会报这个错，可以用最新的试一下
